version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8080   # so frontend calls backend via service name

networks:
  app-network:
    driver: bridge
